[project]
name = "git-helper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "capac", email = "capac@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "httpx>=0.28.1",
    "lxml>=6.1.1",
    "openai>=2.53.0",
    "psycopg2>=2.9.12",
    "python-dotenv>=1.2.2",
    "qdrant-client>=1.19.0",
    "streamlit>=1.61.1",
    "tiktoken>=0.13.0",
]

[project.scripts]
git-helper = "git_helper:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
